modules/admin/controllers/DashboardController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\LoginForm;
use app\modules\admin\models\SystemLog;
use app\modules\admin\models\User;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DashboardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            $this->view->params['user'] = Yii::$app->user->identity;
            Yii::$app->user->loginUrl = ['/admin/dashboard/login'];
            return true;
        } else {
            return false;
        }
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $log = SystemLog::find()->where(['read' => false])->andWhere(['not', ['level' => 4]])->all();
        $counters = [
            'users' => User::find()->count()
        ];

        return $this->render('index', ['log' => $log, 'counters' => $counters]);
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/admin');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/admin');
        }
        return $this->render('login', ['model' => $model,]);
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect('/admin');
    }

    /**
     * @return string
     */
    public function actionError()
    {
        return $this->render('error', [
            'name' => 'Ошибка доступа',
            'message' => 'У вас нет прав на просмотр содержимого этого раздела.',
        ]);
    }
}

modules/admin/controllers/LogController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\models\SystemLog;
use app\modules\admin\models\SystemLogSearch;
use app\modules\admin\Module;
use Yii;
use yii\log\Logger;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LogController implements the CRUD actions for SystemLog model.
 */
class LogController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'clear' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all SystemLog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SystemLogSearch();
        $searchModel->level = Logger::LEVEL_ERROR;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (strcasecmp(Yii::$app->request->method, 'delete') == 0) {
            SystemLog::deleteAll($dataProvider->query->where);
            return $this->refresh();
        }
        $dataProvider->sort = [
            'defaultOrder' => ['log_time' => SORT_DESC]
        ];
        SystemLog::updateAll(['read' => true], ['read' => false]);
        Module::loadLogData();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SystemLog model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $model->read = true;
        $model->save();
        Module::loadLogData();

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SystemLog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the SystemLog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SystemLog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SystemLog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/dashboard/error.php
<?php

use yii\helpers\Html;

/**
 * @var $this yii\web\View
 * @var $name string
 * @var $message string
 * @var $exception Exception
 */

$this->title = $name;
?>
<section class="content">
  <div class="error-page">
    <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>
    <div class="error-content">
      <h3><?= $name ?></h3>
      <p><?= nl2br(Html::encode($message)) ?></p>
    </div>
  </div>
</section>

modules/admin/views/dashboard/index.php
<?php

/**
 * @var $this yii\web\View
 * @var $bestTracks \yii\data\ActiveDataProvider
 * @var $worstTracks \yii\data\ActiveDataProvider
 * @var $log \app\modules\admin\models\SystemLog[]
 * @var $counters array
 * @var $statistics array
 */

use app\modules\admin\models\Article;
use app\modules\admin\models\News;
use app\modules\admin\models\User;
use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Панель управления';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="admin-default-index">
  <div class="row">

    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3><?= User::find()->count() ?></h3>
          <p>Пользователей</p>
        </div>
        <div class="icon">
          <i class="fa fa-user"></i>
        </div>
          <?= Html::a('Все пользователи <i class="fa fa-arrow-circle-right"></i>', ['user/index'], ['class' => 'small-box-footer']); ?>
      </div>
    </div>

    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-green">
        <div class="inner">
          <h3><?= Article::find()->count() ?></h3>
          <p>Статей</p>
        </div>
        <div class="icon">
          <i class="fa fa-file-text"></i>
        </div>
          <?= Html::a('Все статьи <i class="fa fa-arrow-circle-right"></i>', ['article/index'], ['class' => 'small-box-footer']); ?>
      </div>
    </div>

    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-yellow">
        <div class="inner">
          <h3><?= News::find()->count() ?></h3>
          <p>Новостей</p>
        </div>
        <div class="icon">
          <i class="fa fa-file-text"></i>
        </div>
          <?= Html::a('Все новости <i class="fa fa-arrow-circle-right"></i>', ['news/index'], ['class' => 'small-box-footer']); ?>
      </div>
    </div>

    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-red">
        <div class="inner">
          <h3><?= Yii::$app->params['logCount'] ?></h3>
          <p>Новых ошибок</p>
        </div>
        <div class="icon">
          <i class="fa fa-exclamation-triangle"></i>
        </div>
          <?= Html::a('Открыть журнал <i class="fa fa-arrow-circle-right"></i>', ['log/index'], ['class' => 'small-box-footer']); ?>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">
            <?= Html::a(FA::i('list') . ' Создать категорию', ['category/create'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(FA::i('file-text') . ' Создать статью', ['article/create'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(FA::i('file-text') . ' Создать новость', ['news/create'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(FA::i('file-text-o') . ' Создать текстовый блок', ['text-block/create'], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(FA::i('user') . ' Создать пользователя', ['user/create'], ['class' => 'btn btn-primary']) ?>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <h4>Информация о системе</h4>
              <table class="table">
                <tr>
                  <td>Версия Yii2</td>
                  <td><code><?= Yii::getVersion() ?></code></td>
                </tr>
                <tr>
                  <td>Версия PHP</td>
                  <td><code><?= phpversion() ?></code></td>
                </tr>
                <tr>
                  <td>Размер диска</td>
                  <td><code><?= round(disk_total_space(Yii::$app->basePath) / 1024 / 1024 / 1024) ?>
                      Gb</code></td>
                </tr>
                <tr>
                  <td>Свободное место на диске</td>
                  <td><code><?= round(disk_free_space(Yii::$app->basePath) / 1024 / 1024 / 1024) ?> Gb</code></td>
                </tr>
              </table>
            </div>
            <div class="col-md-6">
              <h4>Системный журнал</h4>
              <table class="table">
                  <?php if ($log) { ?>
                      <?php foreach ($log as $record) { ?>
                      <tr>
                        <td><?= Html::encode(date('d.m.Y H:i:s', $record->log_time)) ?></td>
                        <td>
                          <a href="<?= Url::to(['/admin/log/view', 'id' => $record->id]) ?>"><?= Html::encode($record->category) ?></a>
                        </td>
                      </tr>
                      <?php } ?>
                  <?php } else { ?>
                    <tr>
                      <td class="text-muted text-center">Новых записей нет</td>
                    </tr>
                  <?php } ?>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

modules/admin/views/dashboard/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model \app\modules\admin\models\LoginForm
 */

$this->title = 'Панель управления';
?>

<div class="login-box">
  <img src="/images/cp/cp_logo.png" alt="Plum" class="img-responsive">
  <div class="login-box-body">

      <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

      <?= $form->field($model, 'username')->textInput(['placeholder' => 'Логин или Email'])->label(false) ?>

      <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Пароль'])->label(false) ?>

      <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block', 'name' => 'login-button']) ?>

      <?php ActiveForm::end(); ?>
  </div>
</div>